/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ProjetJava;
import javax.swing.table.DefaultTableModel;
import Controller.Produit;
import java.awt.Container;
import java.awt.Image;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author lucas
 */
public class AddOrRemoveProductsFrame extends javax.swing.JFrame {

    private ProjetJava projetjava;
    private EmployeeFrame EmpPage;
    private WelcomeFrame welcomeFrame;
    private LoginVendeursFrame loginvendeursframe;
    private String fileName;
    private String filePath;
    private boolean error;
    private int id_vend;

    /**
     * Creates new form AddOrRemoveProductsFrame
     */
    public AddOrRemoveProductsFrame() {
        initComponents();
    }

    public AddOrRemoveProductsFrame(EmployeeFrame EmpPage, WelcomeFrame welcomeFrame, ProjetJava projetjava, int id_v) {
        initComponents();
        this.projetjava = projetjava;
        this.EmpPage = EmpPage;
        this.welcomeFrame = welcomeFrame;
        this.id_vend = id_v;

        // Chargement des images présentes sur la frame
        ImageIcon fond = new ImageIcon("Fond.png");
        Fond.setIcon(fond);
        ImageIcon search = new ImageIcon("search.png");
        jButton2.setIcon(search);
        ImageIcon del = new ImageIcon("delete.png");
        DeleteBtn.setIcon(del);
        ImageIcon up = new ImageIcon("update.png");
        UpBtn.setIcon(up);
        ImageIcon add = new ImageIcon("add.png");
        AddBtn.setIcon(add);
        ImageIcon ret = new ImageIcon("Retour.png");
        RetBtn.setIcon(ret);
        ImageIcon img = new ImageIcon("imgadd.png");
        jButton1.setIcon(img);

        // Initialisation de la Jtable avec les produits
        DefaultTableModel dm = (DefaultTableModel) Table.getModel();
        dm.getDataVector().removeAllElements();
        dm.fireTableDataChanged();

        // Update la Jtable de produits
        for (int i = 0; i < projetjava.getProduits().size(); i++) {
            String id = String.valueOf(projetjava.getProduits().get(i).getId());
            String nom = projetjava.getProduits().get(i).getNom();
            String prix = String.valueOf(projetjava.getProduits().get(i).getPrix());
            String qter = String.valueOf(projetjava.getProduits().get(i).getQteReduc());
            String prixr = String.valueOf(projetjava.getProduits().get(i).getPrixReduc());

            String Table1[] = {id, nom, prix + " €", qter, prixr + " €"};
            DefaultTableModel Tblmodel = (DefaultTableModel) Table.getModel();
            Tblmodel.addRow(Table1);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        RetBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        p_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        p_Id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        p_price = new javax.swing.JTextField();
        DeleteBtn = new javax.swing.JButton();
        p_qter = new javax.swing.JTextField();
        p_pricer = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        c_searchN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        p_name1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        p_price1 = new javax.swing.JTextField();
        AddBtn = new javax.swing.JButton();
        UpBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        p_Id1 = new javax.swing.JTextField();
        p_qter1 = new javax.swing.JTextField();
        p_pricer1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        FileNameLabel = new javax.swing.JLabel();
        c_searchI = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        Fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Table.setAutoCreateRowSorter(true);
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Product Name", "Price ", "Quantity for reduction", "Reduction price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(590, 20, 600, 210);

        RetBtn.setBackground(new java.awt.Color(207, 199, 216));
        RetBtn.setBorder(null);
        RetBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetBtnActionPerformed(evt);
            }
        });
        getContentPane().add(RetBtn);
        RetBtn.setBounds(10, 580, 100, 50);

        jPanel1.setBackground(new java.awt.Color(207, 199, 216));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name :");

        p_name.setEditable(false);
        p_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        p_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_nameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Id :");

        p_Id.setEditable(false);
        p_Id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Price :");

        p_price.setEditable(false);
        p_price.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        p_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_priceActionPerformed(evt);
            }
        });

        DeleteBtn.setBackground(new java.awt.Color(207, 199, 216));
        DeleteBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DeleteBtn.setText("Delete");
        DeleteBtn.setBorder(null);
        DeleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        p_qter.setEditable(false);
        p_qter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        p_qter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_qterActionPerformed(evt);
            }
        });

        p_pricer.setEditable(false);
        p_pricer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Quantity :");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Reduction price :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p_name)
                    .addComponent(p_Id)
                    .addComponent(p_price)
                    .addComponent(p_qter)
                    .addComponent(p_pricer, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(DeleteBtn)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(p_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_qter, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_pricer)
                    .addComponent(jLabel15))
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 90, 490, 230);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Search name :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(230, 30, 110, 17);

        c_searchN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(c_searchN);
        c_searchN.setBounds(340, 30, 113, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Search id :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 30, 90, 17);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Product Information :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 200, 20);

        jPanel2.setBackground(new java.awt.Color(207, 199, 216));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Name :");

        p_name1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        p_name1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                p_name1ComponentAdded(evt);
            }
        });
        p_name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_name1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Id :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Price :");

        p_price1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        p_price1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_price1ActionPerformed(evt);
            }
        });

        AddBtn.setBackground(new java.awt.Color(207, 199, 216));
        AddBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddBtn.setText("Add");
        AddBtn.setBorder(null);
        AddBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        UpBtn.setBackground(new java.awt.Color(207, 199, 216));
        UpBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UpBtn.setText("Update");
        UpBtn.setBorder(null);
        UpBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpBtnActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Quantity :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Reduction price :");

        p_Id1.setEditable(false);
        p_Id1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        p_Id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_Id1ActionPerformed(evt);
            }
        });

        p_qter1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        p_qter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_qter1ActionPerformed(evt);
            }
        });

        p_pricer1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        p_pricer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_pricer1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(207, 199, 216));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Add image");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_pricer1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_price1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_Id1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_qter1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(UpBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(AddBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FileNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(p_Id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_price1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p_qter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_pricer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(UpBtn)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddBtn)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FileNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 330, 490, 240);

        c_searchI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c_searchI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_searchIActionPerformed(evt);
            }
        });
        getContentPane().add(c_searchI);
        c_searchI.setBounds(100, 30, 113, 20);

        jButton2.setBackground(new java.awt.Color(207, 199, 216));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Search");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(450, 10, 130, 50);

        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel13);
        jLabel13.setBounds(590, 240, 600, 380);
        getContentPane().add(Fond);
        Fond.setBounds(0, 0, 1210, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // mouse click
        // Remplissage des zones de texte a partir de la ligne de la Jtable selectionnée
        int number = Table.getSelectedRow();
        p_name.setText(Table.getValueAt(number, 1).toString());
        p_price.setText(Table.getValueAt(number, 2).toString());
        p_Id.setText(Table.getValueAt(number, 0).toString());
        p_qter.setText(Table.getValueAt(number, 3).toString());
        p_pricer.setText(Table.getValueAt(number, 4).toString());
        p_name1.setText(Table.getValueAt(number, 1).toString());
        p_price1.setText(Table.getValueAt(number, 2).toString());
        p_Id1.setText(Table.getValueAt(number, 0).toString());
        p_qter1.setText(Table.getValueAt(number, 3).toString());
        p_pricer1.setText(Table.getValueAt(number, 4).toString());

        int id = Integer.parseInt(Table.getValueAt(number, 0).toString());

        // AFFICHAGE IMAGE PRODUIT 
        for (int i = 0; i < projetjava.getProduits().size(); i++) {
            if (projetjava.getProduits().get(i).getId() == id) {
                byte[] img = projetjava.getProduits().get(i).getMyImage();
                ImageIcon image = new ImageIcon(img);
                Image im = image.getImage();
                Image imageprod = im.getScaledInstance(jLabel13.getWidth(), jLabel13.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon improd = new ImageIcon(imageprod);
                jLabel13.setIcon(improd);
            }

        }

    }//GEN-LAST:event_TableMouseClicked

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // delete btn code
        int Id = Integer.parseInt(p_Id.getText());
        
        // Suppression produit choisi
        projetjava.deleteProd(projetjava.searchProduit(Id));
        System.out.print("delete successfull");

        DefaultTableModel dm = (DefaultTableModel) Table.getModel();
        dm.getDataVector().removeAllElements();
        dm.fireTableDataChanged();

        // Update la table
        for (int i = 0; i < projetjava.getProduits().size(); i++) {
            String id = String.valueOf(projetjava.getProduits().get(i).getId());
            String nom = projetjava.getProduits().get(i).getNom();
            String prix = String.valueOf(projetjava.getProduits().get(i).getPrix());
            String qter = String.valueOf(projetjava.getProduits().get(i).getQteReduc());
            String prixr = String.valueOf(projetjava.getProduits().get(i).getPrixReduc());

            String Table1[] = {id, nom, prix + " €", qter, prixr + " €"};
            DefaultTableModel Tblmodel = (DefaultTableModel) Table.getModel();
            Tblmodel.addRow(Table1);

        }

        p_name.setText("");
        p_name1.setText("");
        p_Id.setText("");
        p_Id1.setText("");
        p_price.setText("");
        p_price1.setText("");
        p_qter.setText("");
        p_qter1.setText("");
        p_pricer.setText("");
        p_pricer1.setText("");

    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void p_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_nameActionPerformed

    // RECHERCHE PRODUIT PAR ID OU PAR NOM
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // search btn code
        String id = c_searchI.getText();
        String name = c_searchN.getText();

        if (c_searchN.getText().equals("")) {
            for (int i = 0; i < projetjava.getProduits().size(); i++) {

                if (String.valueOf(projetjava.getProduits().get(i).getId()).equals(id)) {

                    p_name.setText(projetjava.getProduits().get(i).getNom());
                    p_Id.setText(String.valueOf(projetjava.getProduits().get(i).getId()));
                    p_price.setText(String.valueOf(projetjava.getProduits().get(i).getPrix()) + " €");
                    p_qter.setText(String.valueOf(projetjava.getProduits().get(i).getQteReduc()));
                    p_pricer.setText(String.valueOf(projetjava.getProduits().get(i).getPrixReduc()) + " €");
                    // System.out.println("test");
                    p_name1.setText(projetjava.getProduits().get(i).getNom());
                    p_Id1.setText(String.valueOf(projetjava.getProduits().get(i).getId()));
                    p_price1.setText(String.valueOf(projetjava.getProduits().get(i).getPrix()) + " €");
                    p_qter1.setText(String.valueOf(projetjava.getProduits().get(i).getQteReduc()));
                    p_pricer1.setText(String.valueOf(projetjava.getProduits().get(i).getPrixReduc()) + " €");
                    c_searchN.setText("");
                    c_searchI.setText("");
                }

            }
        } else if (c_searchI.getText().equals("")) {
            for (int i = 0; i < projetjava.getProduits().size(); i++) {

                if (String.valueOf(projetjava.getProduits().get(i).getNom()).equals(name)) {

                    p_name.setText(projetjava.getProduits().get(i).getNom());
                    p_Id.setText(String.valueOf(projetjava.getProduits().get(i).getId()));
                    p_price.setText(String.valueOf(projetjava.getProduits().get(i).getPrix()) + " €");
                    p_qter.setText(String.valueOf(projetjava.getProduits().get(i).getQteReduc()));
                    p_pricer.setText(String.valueOf(projetjava.getProduits().get(i).getPrixReduc()) + " €");
                    //System.out.println("test");
                    p_name1.setText(projetjava.getProduits().get(i).getNom());
                    p_Id1.setText(String.valueOf(projetjava.getProduits().get(i).getId()));
                    p_price1.setText(String.valueOf(projetjava.getProduits().get(i).getPrix()) + " €");
                    p_qter1.setText(String.valueOf(projetjava.getProduits().get(i).getQteReduc()));
                    p_pricer1.setText(String.valueOf(projetjava.getProduits().get(i).getPrixReduc()) + " €");
                    c_searchN.setText("");
                    c_searchI.setText("");
                }

            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void p_name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_name1ActionPerformed
        // Générateur d'id de produit aléatoire avec la touche entrée
        int Id = idAlea();
        p_Id1.setText(String.valueOf(Id));
    }//GEN-LAST:event_p_name1ActionPerformed

    // AJOUT D'UN PRODUIT
    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        
        boolean test = false;

        if (p_name1.getText().equals("") || p_price1.getText().equals("") || p_Id1.getText().equals("") || p_qter1.getText().equals("") || p_pricer1.getText().equals("")) {
            test = true;
            System.out.println("Erreur création produit");
        }
        if (!test) {
            Produit produit = new Produit(Integer.parseInt(p_Id1.getText()), p_name1.getText(), Double.parseDouble(p_price1.getText()), Integer.parseInt(p_qter1.getText()), Double.parseDouble(p_pricer1.getText()), null);
            projetjava.addProduits(produit);
        }

        // Vide la table 
        DefaultTableModel dm = (DefaultTableModel) Table.getModel();
        dm.getDataVector().removeAllElements();
        dm.fireTableDataChanged();

        // Update la table
        for (int i = 0; i < projetjava.getProduits().size(); i++) {
            String id = String.valueOf(projetjava.getProduits().get(i).getId());
            String nom = projetjava.getProduits().get(i).getNom();
            String prix = String.valueOf(projetjava.getProduits().get(i).getPrix());
            String qter = String.valueOf(projetjava.getProduits().get(i).getQteReduc());
            String prixr = String.valueOf(projetjava.getProduits().get(i).getPrixReduc());

            String Table1[] = {id, nom, prix + " €", qter, prixr + " €"};
            DefaultTableModel Tblmodel = (DefaultTableModel) Table.getModel();
            Tblmodel.addRow(Table1);

        }

    }//GEN-LAST:event_AddBtnActionPerformed

    // ACTUALISATION PRODUIT
    private void UpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpBtnActionPerformed

        int Id = Integer.parseInt(p_Id1.getText());
        String p_Prix = p_price1.getText();
        String Nom = p_name1.getText();
        int Qte_reduc = Integer.parseInt(p_qter1.getText());
        String Prix_reduc0 = p_pricer1.getText();

        double Prix_reduc = Double.parseDouble(Prix_reduc0.replaceAll(" €", ""));
        double Prix = Double.parseDouble(p_Prix.replaceAll(" €", ""));

        boolean test = false;

        if (p_name1.getText().equals("") || p_price1.getText().equals("") || p_Id1.getText().equals("") || p_qter1.getText().equals("") || p_pricer1.getText().equals("")) {
            test = true;
            System.out.println("Erreur maj produit");
        }
        if (!test) {
            projetjava.ReplaceProduit(Id, Prix, Nom, Qte_reduc, Prix_reduc);
        }

        // Vide la table 
        DefaultTableModel dm = (DefaultTableModel) Table.getModel();
        dm.getDataVector().removeAllElements();
        dm.fireTableDataChanged();

        // Update la table
        for (int i = 0; i < projetjava.getProduits().size(); i++) {
            String id = String.valueOf(projetjava.getProduits().get(i).getId());
            String nom = projetjava.getProduits().get(i).getNom();
            String prix = String.valueOf(projetjava.getProduits().get(i).getPrix());
            String qter = String.valueOf(projetjava.getProduits().get(i).getQteReduc());
            String prixr = String.valueOf(projetjava.getProduits().get(i).getPrixReduc());

            String Table1[] = {id, nom, prix + " €", qter, prixr + " €"};
            DefaultTableModel Tblmodel = (DefaultTableModel) Table.getModel();
            Tblmodel.addRow(Table1);
        }

    }//GEN-LAST:event_UpBtnActionPerformed

    private void p_qterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_qterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_qterActionPerformed

    private void p_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_priceActionPerformed

    private void p_Id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_Id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_Id1ActionPerformed

    private void p_qter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_qter1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_qter1ActionPerformed

    private void p_pricer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_pricer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_pricer1ActionPerformed

    private void p_name1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_p_name1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_p_name1ComponentAdded

    private void RetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetBtnActionPerformed
        // Retour frame précédente
        EmployeeFrame emp = new EmployeeFrame(loginvendeursframe, welcomeFrame, projetjava, id_vend);
        welcomeFrame.fullScreen(emp, this);
    }//GEN-LAST:event_RetBtnActionPerformed

    private void p_price1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_price1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_price1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Trouver l'image souhaiter sur son ordinateur

        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & GIF Images & PNG", "jpg", "gif", "png");
        chooser.setFileFilter(filter);

        // we make sure the file can be opened
        int returnVal = chooser.showOpenDialog(new Container());
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            fileName = chooser.getSelectedFile().getName();
            filePath = chooser.getSelectedFile().getPath();
            FileNameLabel.setText(fileName);

            ImageIcon im = new ImageIcon(filePath);
            Image imageprod = im.getImage().getScaledInstance(jLabel13.getWidth(), jLabel13.getHeight(), Image.SCALE_SMOOTH);

            jLabel13.setIcon(new ImageIcon(imageprod));
        } else {
            error = true;
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void c_searchIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_searchIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_searchIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOrRemoveProductsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOrRemoveProductsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOrRemoveProductsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOrRemoveProductsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddOrRemoveProductsFrame().setVisible(true);
            }
        });
    }

    // Générateur id aléatoire entre 1 et 1000 + vérif si existe déjà
    public int idAlea() {

        Random r = new Random();
        int n = r.nextInt(1000);

        for (int i = 0; i < projetjava.getProduits().size(); i++) {
            if (n == projetjava.getProduits().get(i).getId()) {
                idAlea();
                //  System.out.println("erreur");
                //  System.out.println(n);
            }

            //  System.out.println(n); 
        }
        return n;
    }

    // Met la Jtable à jour
    void refresh() {
        // Vide la table 
        DefaultTableModel dm = (DefaultTableModel) Table.getModel();
        dm.getDataVector().removeAllElements();
        dm.fireTableDataChanged();

        // Update la table
        for (int i = 0; i < projetjava.getProduits().size(); i++) {
            String id = String.valueOf(projetjava.getProduits().get(i).getId());
            String nom = projetjava.getProduits().get(i).getNom();
            String prix = String.valueOf(projetjava.getProduits().get(i).getPrix());
            String qter = String.valueOf(projetjava.getProduits().get(i).getQteReduc());
            String prixr = String.valueOf(projetjava.getProduits().get(i).getPrixReduc());

            String Table1[] = {id, nom, prix + " €", qter, prixr + " €"};
            DefaultTableModel Tblmodel = (DefaultTableModel) Table.getModel();
            Tblmodel.addRow(Table1);

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JLabel FileNameLabel;
    private javax.swing.JLabel Fond;
    private javax.swing.JButton RetBtn;
    private javax.swing.JTable Table;
    private javax.swing.JButton UpBtn;
    private javax.swing.JTextField c_searchI;
    private javax.swing.JTextField c_searchN;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField p_Id;
    private javax.swing.JTextField p_Id1;
    private javax.swing.JTextField p_name;
    private javax.swing.JTextField p_name1;
    private javax.swing.JTextField p_price;
    private javax.swing.JTextField p_price1;
    private javax.swing.JTextField p_pricer;
    private javax.swing.JTextField p_pricer1;
    private javax.swing.JTextField p_qter;
    private javax.swing.JTextField p_qter1;
    // End of variables declaration//GEN-END:variables
}
