/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ProjetJava;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucas
 */
public class BuyerFrame extends javax.swing.JFrame {

    /**
     * Creates new form BuyerFrame
     */
    private ProjetJava projetjava;
    private WelcomeFrame welcomeFrame;
    private LoginFrame previous;
    private int IdAcheteur;
    private String nameU;
    private String prenom;

    public BuyerFrame() {
        initComponents();
    }

    public BuyerFrame(WelcomeFrame welcome, ProjetJava projet, LoginFrame previous, int IdAcheteur) {
        initComponents();

        this.projetjava = projet;
        this.welcomeFrame = welcome;
        this.previous = previous;
        this.IdAcheteur = IdAcheteur;

        // Init de la frame
        jPanel1.setVisible(false);

        ImageIcon fond = new ImageIcon("Fond.png");
        Fond.setIcon(fond);
        ImageIcon ret = new ImageIcon("Retour.png");
        RetBtn.setIcon(ret);
        
        String nom = Nom(IdAcheteur);
        String pre = Prénom(IdAcheteur);
        WelLbl.setText("Welcome "+pre+" "+nom);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewOrder = new javax.swing.JButton();
        PreviousOrders = new javax.swing.JButton();
        RetBtn = new javax.swing.JButton();
        WelLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        NewOrder.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        NewOrder.setText("NEW ORDER ");
        NewOrder.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NewOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewOrderActionPerformed(evt);
            }
        });
        getContentPane().add(NewOrder);
        NewOrder.setBounds(230, 230, 810, 60);

        PreviousOrders.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PreviousOrders.setText("ACCES TO YOUR PREVIOUS ORDERS");
        PreviousOrders.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PreviousOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousOrdersActionPerformed(evt);
            }
        });
        getContentPane().add(PreviousOrders);
        PreviousOrders.setBounds(230, 140, 810, 50);

        RetBtn.setBackground(new java.awt.Color(207, 199, 216));
        RetBtn.setBorder(null);
        RetBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetBtnActionPerformed(evt);
            }
        });
        getContentPane().add(RetBtn);
        RetBtn.setBounds(40, 580, 60, 40);

        WelLbl.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        WelLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(WelLbl);
        WelLbl.setBounds(230, 30, 840, 50);

        jPanel1.setBackground(new java.awt.Color(207, 199, 216));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° order", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(340, 320, 570, 200);
        getContentPane().add(Fond);
        Fond.setBounds(0, 0, 1210, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PreviousOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousOrdersActionPerformed
        // AFFICHAGE DES ANCIENNES COMMANDES DE L'UTILISATEUR DANS LA JTABLE
        
        for (int i = 0; i < projetjava.getCommandes().size(); i++) {
            if (projetjava.getCommandes().get(i).getAcheteur() == IdAcheteur) {
                String num_order = String.valueOf(projetjava.getCommandes().get(i).getNumCmd());
                double prix = 0;
                for (int j = 0; j < projetjava.getCommandes().get(i).getPrixProduits().size(); j++) {
                    prix = prix + projetjava.getCommandes().get(i).getPrixProduits().get(j);
                    //System.out.println(projetjava.getCommandes().get(i).getPrixProduits().get(j));

                }
                String price = String.valueOf(prix);
                //System.out.println(price);
                String Table1[] = {num_order, price + " €"};
                DefaultTableModel Tblmodel = (DefaultTableModel) jTable1.getModel();
                Tblmodel.addRow(Table1);
            }
        }
        jPanel1.setVisible(true);
    }//GEN-LAST:event_PreviousOrdersActionPerformed

    private void RetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetBtnActionPerformed
        //Retour frame d'avant
        LoginFrame log = new LoginFrame(welcomeFrame, projetjava);
        welcomeFrame.fullScreen(log, this);
    }//GEN-LAST:event_RetBtnActionPerformed

    private void NewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewOrderActionPerformed
        AchatFrame achat = new AchatFrame(projetjava, 'm', welcomeFrame, previous, IdAcheteur);
        welcomeFrame.fullScreen(achat, this);
    }//GEN-LAST:event_NewOrderActionPerformed

    private String Nom(int id)
    {
        
        for(int i=0;i<projetjava.getAcheteurs().size();i++)
        {
            if(projetjava.getAcheteurs().get(i).getId()==id)
            {
                 nameU = projetjava.getAcheteurs().get(i).getNom();
            }
        }
        return nameU;
    }
    
    private String Prénom(int id)
    {
        
        for(int i=0;i<projetjava.getAcheteurs().size();i++)
        {
            if(projetjava.getAcheteurs().get(i).getId()==id)
            {
                 prenom = projetjava.getAcheteurs().get(i).getPrenom();
            }
        }
        return prenom;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fond;
    private javax.swing.JButton NewOrder;
    private javax.swing.JButton PreviousOrders;
    private javax.swing.JButton RetBtn;
    private javax.swing.JLabel WelLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
