/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Acheteur;
import Controller.Guest;
import Controller.Member;
import Controller.ProjetJava;
import java.util.Random;
import javax.swing.*;

/**
 *
 * @author lucas
 */
public class LoginFrame extends javax.swing.JFrame {

    private ProjetJava projetjava;
    private WelcomeFrame welcomeFrame;

    public LoginFrame() {
        initComponents();
    }

    /**
     * Creates new form Loginpage
     */
    public LoginFrame(WelcomeFrame welcomeFrame, ProjetJava ProjetJava) {
        initComponents();
        this.projetjava = ProjetJava;
        this.welcomeFrame = welcomeFrame;
        
        // Init frame
        LogTest.setVisible(false);

        ImageIcon fond = new ImageIcon("Login.png");
        Fond.setIcon(fond);
        ImageIcon visible = new ImageIcon("View.png");
        View.setIcon(visible);
        ImageIcon caché = new ImageIcon("Hide.png");
        Hide.setIcon(caché);
        Hide.setVisible(false);
        ImageIcon reto = new ImageIcon("Retour.png");
        ret.setIcon(reto);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Id = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ret = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Hide = new javax.swing.JLabel();
        View = new javax.swing.JLabel();
        LogTest = new javax.swing.JLabel();
        Fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setResizable(false);
        getContentPane().setLayout(null);

        Id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdActionPerformed(evt);
            }
        });
        getContentPane().add(Id);
        Id.setBounds(390, 290, 570, 40);

        Password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Password);
        Password.setBounds(420, 400, 520, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Sign In");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(580, 510, 80, 23);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Sign Up");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(580, 540, 80, 23);

        ret.setBackground(new java.awt.Color(207, 199, 216));
        ret.setBorder(null);
        ret.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retActionPerformed(evt);
            }
        });
        getContentPane().add(ret);
        ret.setBounds(30, 570, 60, 60);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Continue as a guest");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(550, 570, 150, 23);

        Hide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Hide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HideMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HideMousePressed(evt);
            }
        });
        getContentPane().add(Hide);
        Hide.setBounds(950, 410, 40, 30);

        View.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        View.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ViewMousePressed(evt);
            }
        });
        getContentPane().add(View);
        View.setBounds(950, 410, 40, 30);

        LogTest.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LogTest.setForeground(new java.awt.Color(255, 51, 51));
        LogTest.setText("CAN'T CONNECT PLEASE CHECK YOUR LOGIN INFORMATION");
        getContentPane().add(LogTest);
        LogTest.setBounds(420, 460, 500, 30);

        Fond.setIcon(new javax.swing.ImageIcon("C:\\Users\\lucas\\Documents\\NetBeansProjects\\Projet Java v.lulu aaa\\Projet Java v.lulu\\Projet Java\\Projet Java\\Login.png")); // NOI18N
        getContentPane().add(Fond);
        Fond.setBounds(0, 0, 1200, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String password = String.valueOf(Password.getPassword());
        String mail = Id.getText();
        boolean test = true;
        boolean TEST = true;
        if (Id.getText().equals("") || Password.getText().equals("")) {
            TEST = false;
            System.out.println("CA MARCHE PAS");
            LogTest.setVisible(true);
        }

        if (TEST) {
            for (int i = 0; i < projetjava.getAcheteurs().size(); i++) {

                if (projetjava.getAcheteurs().get(i).getMail().equals(mail) && projetjava.getAcheteurs().get(i).getMdp().equals(password) && projetjava.getAcheteurs().get(i).getType().equals("m")) {
                    test = false;
                    BuyerFrame achat = new BuyerFrame(welcomeFrame, projetjava, this, projetjava.getAcheteurs().get(i).getId());
                    welcomeFrame.fullScreen(achat, this);

                } else if (test) {
                    System.out.println("erreur d'identifiant");
                    LogTest.setVisible(true);
                }
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SignUpFrame signUp = new SignUpFrame(this, projetjava, welcomeFrame);
        welcomeFrame.fullScreen(signUp, this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void retActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retActionPerformed
        // TODO add your handling code here:
        WelcomeFrame welcome = new WelcomeFrame();
        welcomeFrame.fullScreen(welcome, this);
    }//GEN-LAST:event_retActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        int id = idAlea();
        Acheteur newAch = new Guest(id, "", "", "", "");
        projetjava.addAcheteurs(newAch);

        AchatFrame achat = new AchatFrame(projetjava, 'g', welcomeFrame, this, id);
        welcomeFrame.fullScreen(achat, this);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void HideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HideMouseClicked

    }//GEN-LAST:event_HideMouseClicked

    private void ViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewMouseClicked

    }//GEN-LAST:event_ViewMouseClicked

    private void ViewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewMousePressed
        Password.setEchoChar((char) 0);
        Hide.setVisible(true);
        View.setVisible(false);
    }//GEN-LAST:event_ViewMousePressed

    private void HideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HideMousePressed
        Password.setEchoChar('*');
        Hide.setVisible(false);
        View.setVisible(true);
    }//GEN-LAST:event_HideMousePressed

    public int idAlea() {

        Random r = new Random();
        int n = r.nextInt(1000);

        for (int i = 0; i < projetjava.getAcheteurs().size(); i++) {
            if (n == projetjava.getAcheteurs().get(i).getId()) {
                idAlea();
            }
        }
        return n;
    }

    /*public int CmdAlea()
         {
        Random r = new Random();
        int n = r.nextInt(1000);
        
        for (int i=0;i<projetjava.getAcheteurs().size();i++)
        {
            if(n==projetjava.getAcheteurs().get(i).getCmd())
                CmdAlea();
        }
       // System.out.println(n); 
        return n;
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new LoginFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fond;
    private javax.swing.JLabel Hide;
    private javax.swing.JTextField Id;
    private javax.swing.JLabel LogTest;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel View;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton ret;
    // End of variables declaration//GEN-END:variables
}
