/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Commande;
import Controller.Email;
import Controller.ProjetJava;
import static java.lang.System.exit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class PaymentFrame extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    int num_cmd;
    private WelcomeFrame welcome;
    private ProjetJava projetjava;
    private Commande cmd;
    private AchatFrame previous;
    private char type;
    private int idAcheteur;
    private LoginFrame loginF;

    public PaymentFrame() {
        initComponents();
    }

    public PaymentFrame(WelcomeFrame welcome, AchatFrame previous, ProjetJava projetjava, int _cmd, Commande commande, char type, int Id, LoginFrame _loginF) {
        initComponents();

        this.welcome = welcome;
        this.num_cmd = _cmd;
        this.projetjava = projetjava;
        this.loginF = _loginF;
        this.cmd = commande;
        this.previous = previous;
        this.type = type;
        this.idAcheteur = Id;

        jLabel1.setVisible(false);

        ImageIcon fond = new ImageIcon("Payment.png");
        Fond.setIcon(fond);
        ImageIcon ret = new ImageIcon("Retour.png");
        RetBtn.setIcon(ret);

        ///Récupérer la commande de la précédente frame et calculer le prix
        //NE PAS OUBLIER DE CHECK SI C'EST UN MEMBRE OU UN GUEST
        //LES GUEST N'ONT PAS LES REDUCTIONS
        double pricetopay = 0;
        for (int i = 0; i < cmd.getPrixProduits().size(); i++) {

            pricetopay = pricetopay + cmd.getPrixProduits().get(i);

        }

        /*
        if (acheteur.getType().equals("m")) {
        //c'est un membre donc droit aux réducs
            
        }else {
        //c'est un invité donc pas de reduc
        }
         */
        Price.setText(Double.toString(pricetopay) + " €");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RetBtn = new javax.swing.JButton();
        NameCC = new javax.swing.JTextField();
        NumCC = new javax.swing.JTextField();
        CVV = new javax.swing.JTextField();
        Year = new javax.swing.JComboBox<>();
        Month = new javax.swing.JComboBox<>();
        PayBtn = new javax.swing.JButton();
        Price = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        RetBtn.setBackground(new java.awt.Color(207, 199, 216));
        RetBtn.setBorder(null);
        RetBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetBtnActionPerformed(evt);
            }
        });
        getContentPane().add(RetBtn);
        RetBtn.setBounds(20, 570, 77, 60);

        NameCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(NameCC);
        NameCC.setBounds(390, 220, 580, 30);

        NumCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(NumCC);
        NumCC.setBounds(390, 280, 580, 30);

        CVV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(CVV);
        CVV.setBounds(390, 340, 580, 30);

        Year.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041" }));
        getContentPane().add(Year);
        Year.setBounds(430, 410, 90, 21);

        Month.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(Month);
        Month.setBounds(380, 410, 40, 21);

        PayBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PayBtn.setText("Pay");
        PayBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PayBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayBtnActionPerformed(evt);
            }
        });
        getContentPane().add(PayBtn);
        PayBtn.setBounds(1020, 540, 110, 30);

        Price.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Price.setText("0");
        getContentPane().add(Price);
        Price.setBounds(600, 540, 310, 60);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("PLEASE CHECK YOUR PAYMENT INFORMATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(390, 440, 580, 40);

        Fond.setIcon(new javax.swing.ImageIcon("C:\\Users\\lucas\\Documents\\NetBeansProjects\\Projet Java v.lulu aaa\\Projet Java v.lulu\\Projet Java\\Projet Java\\Payment.png")); // NOI18N
        Fond.setText("jLabel1");
        getContentPane().add(Fond);
        Fond.setBounds(0, 0, 1200, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayBtnActionPerformed
        // TODO add your handling code here:
        boolean test = true;
        String nom = "", prenom = "", mail = "";
        //Verifie que les champs ne sont pas vides
        //Verifie que le n° de CC contient 16 caractères
        //Vérifie que le CVV contient 3 caractères
        if (NameCC.getText().equals("") || CVV.getText().length() != 3 || NumCC.getText().replaceAll("\\s", "").length() != 16 || NumCC.getText().equals("") || CVV.getText().equals("")) {
            test = false;
            jLabel1.setVisible(true);

            System.out.println("Les coordonnées bancaires n'ont pas été saisies correctement");
        }
        if (test) {
            Email m = new Email();
            for (int i = 0; i < projetjava.getAcheteurs().size(); i++) {
                if (projetjava.getAcheteurs().get(i).getId() == idAcheteur) {
                    nom = projetjava.getAcheteurs().get(i).getNom();
                    prenom = projetjava.getAcheteurs().get(i).getPrenom();
                    mail = projetjava.getAcheteurs().get(i).getMail();
                }
            }
            m.sendEmail(cmd, nom, prenom, mail, projetjava.getProduits());

            JOptionPane d = new JOptionPane();
            d.showMessageDialog(this, "Payment complete", "Payment", JOptionPane.INFORMATION_MESSAGE);
            projetjava.addCommande(this.cmd);
            WelcomeFrame retur = new WelcomeFrame();
            welcome.fullScreen(retur, this);

        }
    }//GEN-LAST:event_PayBtnActionPerformed

    private void RetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetBtnActionPerformed

        AchatFrame back = new AchatFrame(projetjava, type, welcome, loginF, idAcheteur);

        welcome.fullScreen(back, this);

    }//GEN-LAST:event_RetBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CVV;
    private javax.swing.JLabel Fond;
    private javax.swing.JComboBox<String> Month;
    private javax.swing.JTextField NameCC;
    private javax.swing.JTextField NumCC;
    private javax.swing.JButton PayBtn;
    private javax.swing.JLabel Price;
    private javax.swing.JButton RetBtn;
    private javax.swing.JComboBox<String> Year;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
