/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ProjetJava;
import Controller.*;
import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author lucas
 */
public class SignUpFrame extends javax.swing.JFrame {

    /**
     * Creates new form SignUpFrame
     */
    private LoginFrame login;
    private EmployeeFrame employee;
    private ProjetJava projet;
    private int id;
    private WelcomeFrame welcomeFrame;
    private char tipe;
    private LoginVendeursFrame loginV;
    private int id_vend;

    public SignUpFrame() {
        initComponents();
    }

    public SignUpFrame(LoginFrame login, ProjetJava projet, WelcomeFrame welcomeFrame) {

        initComponents();
        this.login = login;
        this.projet = projet;
        this.welcomeFrame = welcomeFrame;
        ImageIcon Fond = new ImageIcon("SignIn.png");
        fond.setIcon(Fond);
        SignUpTest.setVisible(false);
    }

    public SignUpFrame(EmployeeFrame employee, ProjetJava projet, WelcomeFrame welcomeFrame, char tipe, int id_vend) {

        initComponents();
        this.employee = employee;
        this.projet = projet;
        this.welcomeFrame = welcomeFrame;
        ImageIcon Fond = new ImageIcon("SignIn.png");
        fond.setIcon(Fond);
        this.tipe = tipe;
        this.id_vend = id_vend;
        SignUpTest.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Register = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        LastName = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        FirstName = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        ConfirmPassword = new javax.swing.JPasswordField();
        SignUpTest = new javax.swing.JLabel();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Register.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Register.setText("Sign Up");
        Register.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        getContentPane().add(Register);
        Register.setBounds(500, 570, 120, 40);

        Cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel);
        Cancel.setBounds(680, 570, 140, 40);

        LastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameActionPerformed(evt);
            }
        });
        getContentPane().add(LastName);
        LastName.setBounds(350, 240, 640, 30);

        Email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(Email);
        Email.setBounds(350, 370, 660, 30);

        FirstName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(FirstName);
        FirstName.setBounds(350, 310, 630, 30);

        Password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Password);
        Password.setBounds(350, 440, 640, 30);

        ConfirmPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(ConfirmPassword);
        ConfirmPassword.setBounds(440, 500, 560, 30);

        SignUpTest.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SignUpTest.setForeground(new java.awt.Color(255, 51, 51));
        SignUpTest.setText("CAN'T SIGN UP PLEASE CHECK YOUR LOGIN INFORMATION");
        getContentPane().add(SignUpTest);
        SignUpTest.setBounds(470, 530, 500, 30);

        fond.setIcon(new javax.swing.ImageIcon("C:\\Users\\lucas\\Documents\\NetBeansProjects\\Projet Java v.lulu aaa\\Projet Java v.lulu\\Projet Java\\Projet Java\\SignIn.png")); // NOI18N
        getContentPane().add(fond);
        fond.setBounds(0, 0, 1210, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPasswordActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_ConfirmPasswordActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        // TODO add your handling code here:
        id = idAlea();
        boolean test = false;

        if (LastName.getText().equals("") || FirstName.getText().equals("") || Email.getText().equals("") || Password.getText().equals("") || ConfirmPassword.getText().equals("") || !Password.getText().equals(ConfirmPassword.getText())) {
            test = true;
            System.out.println("Erreur membre");
            SignUpTest.setVisible(true);
        }
        if (!test) {
            //  Acheteur newAch = new Member(id, Password.getText(), Email.getText(), LastName.getText(), FirstName.getText());
            //  projet.addAcheteurs(newAch);

            if (tipe == 'e') {
                Vendeur newV = new Vendeur(id, Password.getText(), Email.getText(), LastName.getText(), FirstName.getText());
                projet.addVendeurs(newV);
                EmployeeFrame emp = new EmployeeFrame(loginV, welcomeFrame, projet, id_vend);
                welcomeFrame.fullScreen(emp, this);
            } else if (tipe != 'e') {
                Acheteur newAch = new Member(id, Password.getText(), Email.getText(), LastName.getText(), FirstName.getText());
                projet.addAcheteurs(newAch);
                LoginFrame log = new LoginFrame(welcomeFrame, projet);
                welcomeFrame.fullScreen(log, this);
            }

        }

    }//GEN-LAST:event_RegisterActionPerformed

    private void LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        if (tipe == 'e') {
            EmployeeFrame emp = new EmployeeFrame(loginV, welcomeFrame, projet, id_vend);
            welcomeFrame.fullScreen(emp, this);
        } else {
            LoginFrame log = new LoginFrame(welcomeFrame, projet);
            welcomeFrame.fullScreen(log, this);
        }
    }//GEN-LAST:event_CancelActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    public int idAlea() {

        Random r = new Random();
        int n = r.nextInt(1000);

        for (int i = 0; i < projet.getAcheteurs().size(); i++) {
            if (n == projet.getAcheteurs().get(i).getId()) {
                idAlea();
                //  System.out.println("erreur");
                //  System.out.println(n);
            }

            //  System.out.println(n); 
        }
        return n;
    }

    /*public int CmdAlea()
         {
        Random r = new Random();
        int n = r.nextInt(1000);
        
        for (int i=0;i<projet.getAcheteurs().size();i++)
        {
            if(n==projet.getAcheteurs().get(i).getCmd())
                CmdAlea();
        }
       // System.out.println(n); 
        return n;
    } */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SignUpFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JPasswordField ConfirmPassword;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField FirstName;
    private javax.swing.JTextField LastName;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton Register;
    private javax.swing.JLabel SignUpTest;
    private javax.swing.JLabel fond;
    // End of variables declaration//GEN-END:variables
}
