/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ProjetJava;
import Controller.Vendeur;
import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author lenaheurtaux
 */
public class SignUpEmployeeFrame extends javax.swing.JFrame {

    private EmployeeFrame employee;
    private ProjetJava projet;
    private LoginVendeursFrame loginvendeursframe;
    private WelcomeFrame welcomeFrame;
    private int id;

    /**
     * Creates new form SignUpEmployee
     */
    public SignUpEmployeeFrame() {
        initComponents();
    }

    public SignUpEmployeeFrame(EmployeeFrame employee, ProjetJava projet) {
        initComponents();
        this.employee = employee;
        this.projet = projet;
        ImageIcon Fond = new ImageIcon("SignIn.png");
        fond.setIcon(Fond);
        ImageIcon ret = new ImageIcon("Retour.png");
        RetBtn.setIcon(ret);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LastName = new javax.swing.JTextField();
        FirstName = new javax.swing.JTextField();
        Mail = new javax.swing.JTextField();
        ConfirmPassword = new javax.swing.JPasswordField();
        Password = new javax.swing.JPasswordField();
        RetBtn = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        LastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameActionPerformed(evt);
            }
        });
        getContentPane().add(LastName);
        LastName.setBounds(360, 230, 490, 40);

        FirstName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameActionPerformed(evt);
            }
        });
        getContentPane().add(FirstName);
        FirstName.setBounds(360, 300, 490, 40);

        Mail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MailActionPerformed(evt);
            }
        });
        getContentPane().add(Mail);
        Mail.setBounds(360, 360, 490, 40);

        ConfirmPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(ConfirmPassword);
        ConfirmPassword.setBounds(440, 490, 410, 40);

        Password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(Password);
        Password.setBounds(360, 420, 490, 40);

        RetBtn.setBackground(new java.awt.Color(207, 199, 216));
        RetBtn.setBorder(null);
        RetBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetBtnActionPerformed(evt);
            }
        });
        getContentPane().add(RetBtn);
        RetBtn.setBounds(30, 560, 130, 50);

        Save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Save.setText("Save");
        Save.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        getContentPane().add(Save);
        Save.setBounds(710, 570, 100, 20);

        fond.setIcon(new javax.swing.ImageIcon("C:\\Users\\lucas\\Documents\\NetBeansProjects\\Projet Java v.lulu aaa\\Projet Java v.lulu\\Projet Java\\Projet Java\\SignIn.png")); // NOI18N
        getContentPane().add(fond);
        fond.setBounds(-5, -4, 1210, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameActionPerformed

    private void FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameActionPerformed

    private void MailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MailActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        id = idAlea();
        boolean test = false;

        if (LastName.getText().equals("") || FirstName.getText().equals("") || Mail.getText().equals("") || Password.getText().equals("") || ConfirmPassword.getText().equals("") || !Password.getText().equals(ConfirmPassword.getText())) {
            test = true;
            System.out.println("Erreur membre");
        }
        if (!test) {
            Vendeur newVendeur = new Vendeur(id, Password.getText(), Mail.getText(), LastName.getText(), FirstName.getText());
            projet.addVendeurs(newVendeur);
            EmployeeFrame emp = new EmployeeFrame(loginvendeursframe, welcomeFrame, projet, id);
            welcomeFrame.fullScreen(emp, this);
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void RetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetBtnActionPerformed

        EmployeeFrame emp = new EmployeeFrame(loginvendeursframe, welcomeFrame, projet, id);
        welcomeFrame.fullScreen(emp, this);
    }//GEN-LAST:event_RetBtnActionPerformed

    public int idAlea() {

        Random r = new Random();
        int n = r.nextInt(1000);

        for (int i = 0; i < projet.getVendeurs().size(); i++) {
            if (n == projet.getVendeurs().get(i).getId()) {
                idAlea();
                //  System.out.println("erreur");
                //  System.out.println(n);
            }

            //  System.out.println(n); 
        }
        return n;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpEmployeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpEmployeeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmPassword;
    private javax.swing.JTextField FirstName;
    private javax.swing.JTextField LastName;
    private javax.swing.JTextField Mail;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton RetBtn;
    private javax.swing.JButton Save;
    private javax.swing.JLabel fond;
    // End of variables declaration//GEN-END:variables
}
